services:
  mariadb:
    image: mariadb:11
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      MARIADB_DATABASE: "tpnode"

  backend:
    #build: .
    image: node:22
    ports:
      - "3000:3000"

    volumes:
      - ./app:/app
    depends_on:
      - mariadb
    command: 'sh -c "cd /app && npm run start"'
